name: Deploy to AWS S3

run-name: Deploy postmanpatdev to S3

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install Project Dependencies
        run: npm i --force

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@^5.11

      - name: Install Gatsby Plugin S3
        run: npm install gatsby-plugin-s3 --force

      - name: Configure AWS CLI Credentials
        run: aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" && aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" && aws configure set region "$AWS_DEFAULT_REGION" && aws configure set output "json"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-southeast-2"

      - name: test variabled
        run: echo "$AWS_ACCESS_KEY_ID"

      - name: Deploy to S3
        run: npm run build
